<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chummer.Application\Chummer.Application.csproj" />
    <ProjectReference Include="..\Chummer.Contracts\Chummer.Contracts.csproj" />
    <ProjectReference Include="..\Chummer.Rulesets.Hosting\Chummer.Rulesets.Hosting.csproj" />
    <ProjectReference Include="..\Chummer.Rulesets.Sr5\Chummer.Rulesets.Sr5.csproj" />
    <ProjectReference Include="..\Chummer.Rulesets.Sr6\Chummer.Rulesets.Sr6.csproj" />
    <Reference Include="Chummer.Hub.Registry.Contracts">
      <HintPath>..\..\chummer-hub-registry\Chummer.Hub.Registry.Contracts\bin\$(Configuration)\net10.0\Chummer.Hub.Registry.Contracts.dll</HintPath>
    </Reference>
    <Reference Include="Chummer.Run.Contracts">
      <HintPath>..\..\chummer.run-services\Chummer.Run.Contracts\bin\$(Configuration)\net10.0\Chummer.Run.Contracts.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="DependencyInjection/ServiceCollectionExtensions.cs" />
  </ItemGroup>
</Project>
